//! HMI path-vocabulary translation shim.
//!
//! The web HMI speaks the project's legacy signal vocabulary
//! (`Body.*` / `Cabin.*` / `Chassis.*`), while the bus is now on the
//! canonical / project namespaces decided in the VSS v6.0 refresh
//! (`Vehicle.*` / `Vehicle.Controller.*` / `Vehicle.Simulation.*`).
//!
//! Rather than rename the HMI's compositional path construction
//! (prefix props, template literals, string concat — ~270 references
//! that a literal rename can't safely reach), we translate at the
//! WebSocket boundary in `ws_bridge`:
//!
//!   - **outbound** (bus → HMI): canonical key → legacy key via
//!     [`to_hmi`], so the HMI's `s["Body.Hood.IsOpen"]` lookups resolve.
//!   - **inbound** (HMI → bus): legacy `path` → canonical via
//!     [`from_hmi`], so it matches the canonical `INPUT_SIGNALS` list.
//!
//! Paths with no alias (already-canonical signals, or HMI-only display
//! paths that never cross the bus) pass through unchanged.
//!
//! This table is generated from `docs/vss-v6.0-path-mapping.csv` with
//! the KeyFob/BlePhone/NfcCard simplification folded in.  When the HMI
//! is itself canonicalised (a future, Playwright-verified sub-PR) this
//! whole module is deleted.

use crate::signal_bus::VssPath;

/// `(canonical bus path, legacy HMI path)` for every signal that
/// crosses the WebSocket boundary in a renamed form.
const HMI_ALIASES: &[(VssPath, VssPath)] = &[
    ("Vehicle.Body.Hood.IsOpen", "Body.Hood.IsOpen"),
    ("Vehicle.Body.Horn.IsActive", "Body.Horn.IsActive"),
    (
        "Vehicle.Body.Lights.Backup.IsOn",
        "Body.Lights.Backup.IsActive",
    ),
    (
        "Vehicle.Body.Lights.Beam.High.IsOn",
        "Body.Lights.Beam.High.IsOn",
    ),
    (
        "Vehicle.Body.Lights.Beam.Low.IsOn",
        "Body.Lights.Beam.Low.IsOn",
    ),
    (
        "Vehicle.Body.Lights.Brake.IsActive",
        "Body.Lights.Brake.IsActive",
    ),
    (
        "Vehicle.Body.Lights.DirectionIndicator.Left.IsSignaling",
        "Body.Lights.DirectionIndicator.Left.IsSignaling",
    ),
    (
        "Vehicle.Body.Lights.DirectionIndicator.Right.IsSignaling",
        "Body.Lights.DirectionIndicator.Right.IsSignaling",
    ),
    (
        "Vehicle.Body.Lights.Fog.Front.IsOn",
        "Body.Lights.Fog.Front.IsOn",
    ),
    (
        "Vehicle.Body.Lights.Fog.Rear.IsOn",
        "Body.Lights.Fog.Rear.IsOn",
    ),
    (
        "Vehicle.Body.Lights.Hazard.IsSignaling",
        "Body.Lights.Hazard.IsSignaling",
    ),
    (
        "Vehicle.Body.Lights.LicensePlate.IsOn",
        "Body.Lights.LicensePlate.IsOn",
    ),
    ("Vehicle.Body.Lights.LightSwitch", "Body.Lights.LightSwitch"),
    (
        "Vehicle.Body.Lights.Parking.IsOn",
        "Body.Lights.Parking.IsOn",
    ),
    (
        "Vehicle.Body.Lights.Running.IsOn",
        "Body.Lights.Running.IsOn",
    ),
    (
        "Vehicle.Body.Mirrors.Left.IsFolded",
        "Body.Mirror.Left.IsFolded",
    ),
    (
        "Vehicle.Body.Mirrors.Left.IsHeatingOn",
        "Body.Mirror.Left.IsHeatingOn",
    ),
    ("Vehicle.Body.Mirrors.Left.Tilt", "Body.Mirror.Left.Tilt"),
    ("Vehicle.Body.Mirrors.Left.Yaw", "Body.Mirror.Left.Yaw"),
    (
        "Vehicle.Body.Mirrors.Right.IsFolded",
        "Body.Mirror.Right.IsFolded",
    ),
    (
        "Vehicle.Body.Mirrors.Right.IsHeatingOn",
        "Body.Mirror.Right.IsHeatingOn",
    ),
    ("Vehicle.Body.Mirrors.Right.Tilt", "Body.Mirror.Right.Tilt"),
    ("Vehicle.Body.Mirrors.Right.Yaw", "Body.Mirror.Right.Yaw"),
    ("Vehicle.Body.Trunk.Rear.IsLocked", "Body.Trunk.IsLocked"),
    ("Vehicle.Body.Trunk.Rear.IsOpen", "Body.Trunk.IsOpen"),
    (
        "Vehicle.Body.Windshield.Front.Wiping.Intensity",
        "Body.Windshield.Front.Wiping.Intensity",
    ),
    (
        "Vehicle.Body.Windshield.Front.Wiping.Mode",
        "Body.Windshield.Front.Wiping.Mode",
    ),
    (
        "Vehicle.Body.Windshield.Rear.Wiping.Mode",
        "Body.Windshield.Rear.Wiping.Mode",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.CloseCmd",
        "Body.Doors.Row1.Left.CloseCmd",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Handle.Inside.IsPulled",
        "Body.Doors.Row1.Left.Handle.Inside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Handle.Outside.IsPulled",
        "Body.Doors.Row1.Left.Handle.Outside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Handle.Outside.LockPad.IsPressed",
        "Body.Doors.Row1.Left.Handle.Outside.LockPad.IsPressed",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.IsChildLockActive",
        "Body.Doors.Row1.Left.IsChildLockActive",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.IsDoubleLocked",
        "Body.Doors.Row1.Left.IsDoubleLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.IsLocked",
        "Body.Doors.Row1.Left.IsLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.IsOpen",
        "Body.Doors.Row1.Left.IsOpen",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.IsRemoved",
        "Body.Doors.Row1.Left.IsRemoved",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Latch.IsLatched",
        "Body.Doors.Row1.Left.Latch.IsLatched",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.LatchStatus",
        "Body.Doors.Row1.Left.LatchStatus",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Soldier.IsUnlocked",
        "Body.Doors.Row1.Left.Soldier.IsUnlocked",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Window.MotorDirection",
        "Body.Doors.Row1.Left.Window.MotorDirection",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Window.Position",
        "Body.Doors.Row1.Left.Window.Position",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.CloseCmd",
        "Body.Doors.Row1.Right.CloseCmd",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Handle.Inside.IsPulled",
        "Body.Doors.Row1.Right.Handle.Inside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Handle.Outside.IsPulled",
        "Body.Doors.Row1.Right.Handle.Outside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Handle.Outside.LockPad.IsPressed",
        "Body.Doors.Row1.Right.Handle.Outside.LockPad.IsPressed",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.IsChildLockActive",
        "Body.Doors.Row1.Right.IsChildLockActive",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.IsDoubleLocked",
        "Body.Doors.Row1.Right.IsDoubleLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.IsLocked",
        "Body.Doors.Row1.Right.IsLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.IsOpen",
        "Body.Doors.Row1.Right.IsOpen",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.IsRemoved",
        "Body.Doors.Row1.Right.IsRemoved",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Latch.IsLatched",
        "Body.Doors.Row1.Right.Latch.IsLatched",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.LatchStatus",
        "Body.Doors.Row1.Right.LatchStatus",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Soldier.IsUnlocked",
        "Body.Doors.Row1.Right.Soldier.IsUnlocked",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Window.MotorDirection",
        "Body.Doors.Row1.Right.Window.MotorDirection",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Window.Position",
        "Body.Doors.Row1.Right.Window.Position",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.CloseCmd",
        "Body.Doors.Row2.Left.CloseCmd",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Handle.Inside.IsPulled",
        "Body.Doors.Row2.Left.Handle.Inside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Handle.Outside.IsPulled",
        "Body.Doors.Row2.Left.Handle.Outside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.IsChildLockActive",
        "Body.Doors.Row2.Left.IsChildLockActive",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.IsDoubleLocked",
        "Body.Doors.Row2.Left.IsDoubleLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.IsLocked",
        "Body.Doors.Row2.Left.IsLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.IsOpen",
        "Body.Doors.Row2.Left.IsOpen",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.IsRemoved",
        "Body.Doors.Row2.Left.IsRemoved",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Latch.IsLatched",
        "Body.Doors.Row2.Left.Latch.IsLatched",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.LatchStatus",
        "Body.Doors.Row2.Left.LatchStatus",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Soldier.IsUnlocked",
        "Body.Doors.Row2.Left.Soldier.IsUnlocked",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Window.MotorDirection",
        "Body.Doors.Row2.Left.Window.MotorDirection",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Window.Position",
        "Body.Doors.Row2.Left.Window.Position",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.CloseCmd",
        "Body.Doors.Row2.Right.CloseCmd",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Handle.Inside.IsPulled",
        "Body.Doors.Row2.Right.Handle.Inside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Handle.Outside.IsPulled",
        "Body.Doors.Row2.Right.Handle.Outside.IsPulled",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.IsChildLockActive",
        "Body.Doors.Row2.Right.IsChildLockActive",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.IsDoubleLocked",
        "Body.Doors.Row2.Right.IsDoubleLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.IsLocked",
        "Body.Doors.Row2.Right.IsLocked",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.IsOpen",
        "Body.Doors.Row2.Right.IsOpen",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.IsRemoved",
        "Body.Doors.Row2.Right.IsRemoved",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Latch.IsLatched",
        "Body.Doors.Row2.Right.Latch.IsLatched",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.LatchStatus",
        "Body.Doors.Row2.Right.LatchStatus",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Soldier.IsUnlocked",
        "Body.Doors.Row2.Right.Soldier.IsUnlocked",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Window.MotorDirection",
        "Body.Doors.Row2.Right.Window.MotorDirection",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Window.Position",
        "Body.Doors.Row2.Right.Window.Position",
    ),
    (
        "Vehicle.Cabin.HVAC.IsAirConditioningActive",
        "Cabin.HVAC.IsAirConditioningActive",
    ),
    (
        "Vehicle.Cabin.HVAC.IsFrontDefrosterActive",
        "Cabin.HVAC.IsFrontDefrosterActive",
    ),
    (
        "Vehicle.Cabin.HVAC.IsRearDefrosterActive",
        "Cabin.HVAC.IsRearDefrosterActive",
    ),
    (
        "Vehicle.Cabin.HVAC.IsRecirculationActive",
        "Cabin.HVAC.IsRecirculationActive",
    ),
    (
        "Vehicle.Cabin.HVAC.Station.Row1.Left.AirDistribution",
        "Cabin.HVAC.Station.Row1.Left.AirDistribution",
    ),
    (
        "Vehicle.Cabin.HVAC.Station.Row1.Left.FanSpeed",
        "Cabin.HVAC.Station.Row1.Left.FanSpeed",
    ),
    (
        "Vehicle.Cabin.HVAC.Station.Row1.Left.Temperature",
        "Cabin.HVAC.Station.Row1.Left.Temperature",
    ),
    (
        "Vehicle.Cabin.HVAC.Station.Row1.Right.AirDistribution",
        "Cabin.HVAC.Station.Row1.Right.AirDistribution",
    ),
    (
        "Vehicle.Cabin.HVAC.Station.Row1.Right.FanSpeed",
        "Cabin.HVAC.Station.Row1.Right.FanSpeed",
    ),
    (
        "Vehicle.Cabin.HVAC.Station.Row1.Right.Temperature",
        "Cabin.HVAC.Station.Row1.Right.Temperature",
    ),
    ("Vehicle.Cabin.Light.IsDomeOn", "Cabin.Lights.IsDomeOn"),
    (
        "Vehicle.Cabin.Light.IsGloveBoxOn",
        "Cabin.Lights.IsGloveBoxOn",
    ),
    (
        "Vehicle.Cabin.Seat.Row1.Left.HeatingCooling",
        "Cabin.Seat.Row1.Left.HeatingLevel",
    ),
    (
        "Vehicle.Cabin.Seat.Row1.Right.HeatingCooling",
        "Cabin.Seat.Row1.Right.HeatingLevel",
    ),
    ("Vehicle.Cabin.Sunroof.Position", "Body.Sunroof.Position"),
    (
        "Vehicle.Cabin.Sunroof.Shade.Position",
        "Body.Sunroof.Shade.Position",
    ),
    (
        "Vehicle.Chassis.Brake.PedalPosition",
        "Chassis.Brake.PedalPosition",
    ),
    (
        "Vehicle.Chassis.ParkingBrake.IsEngaged",
        "Chassis.ParkingBrake.IsEngaged",
    ),
    (
        "Vehicle.ADAS.HighBeam.OncomingVehicleDetected",
        "Vehicle.ADAS.HighBeam.OncomingVehicleDetected",
    ),
    ("Vehicle.Body.Alarm.IsActive", "Vehicle.Body.Alarm.IsActive"),
    ("Vehicle.Controller.Alarm.State", "Vehicle.Body.Alarm.State"),
    ("Vehicle.Body.ChargeLid.IsOpen", "Body.ChargeLid.IsOpen"),
    (
        "Vehicle.Controller.Body.Chime.IsActive",
        "Body.Chime.IsActive",
    ),
    (
        "Vehicle.Controller.Body.Chime.IsSounding",
        "Body.Chime.IsSounding",
    ),
    (
        "Vehicle.Controller.Body.Doors.AutoRelock.IsArmed",
        "Body.Doors.AutoRelock.IsArmed",
    ),
    (
        "Vehicle.Controller.Body.Doors.AutoRelock.TimeoutSeconds",
        "Body.Doors.AutoRelock.TimeoutSeconds",
    ),
    (
        "Vehicle.Controller.Body.Doors.CentralLock.Command",
        "Body.Doors.CentralLock.Command",
    ),
    (
        "Vehicle.Controller.Body.Doors.CentralLock.FeedbackRequest",
        "Body.Doors.CentralLock.FeedbackRequest",
    ),
    ("Vehicle.Body.FuelLid.IsOpen", "Body.FuelLid.IsOpen"),
    (
        "Vehicle.Controller.Body.Hood.CloseCmd",
        "Body.Hood.CloseCmd",
    ),
    ("Vehicle.Body.Hood.LatchState", "Body.Hood.LatchState"),
    ("Vehicle.Controller.Body.Hood.OpenCmd", "Body.Hood.OpenCmd"),
    (
        "Vehicle.Controller.Body.Lights.AmbientLightSensor.Illuminance",
        "Body.Lights.AmbientLightSensor.Illuminance",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Left.Lamp.Front.IsDefect",
        "Body.Lights.DirectionIndicator.Left.Lamp.Front.IsDefect",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Left.Lamp.Front.IsOn",
        "Body.Lights.DirectionIndicator.Left.Lamp.Front.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsDefect",
        "Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsDefect",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsOn",
        "Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Left.Lamp.Side.IsDefect",
        "Body.Lights.DirectionIndicator.Left.Lamp.Side.IsDefect",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Left.Lamp.Side.IsOn",
        "Body.Lights.DirectionIndicator.Left.Lamp.Side.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Right.Lamp.Front.IsDefect",
        "Body.Lights.DirectionIndicator.Right.Lamp.Front.IsDefect",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Right.Lamp.Front.IsOn",
        "Body.Lights.DirectionIndicator.Right.Lamp.Front.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsDefect",
        "Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsDefect",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsOn",
        "Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Right.Lamp.Side.IsDefect",
        "Body.Lights.DirectionIndicator.Right.Lamp.Side.IsDefect",
    ),
    (
        "Vehicle.Controller.Body.Lights.DirectionIndicator.Right.Lamp.Side.IsOn",
        "Body.Lights.DirectionIndicator.Right.Lamp.Side.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Lights.Puddle.Left.IsOn",
        "Body.Lights.Puddle.Left.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Lights.Puddle.Right.IsOn",
        "Body.Lights.Puddle.Right.IsOn",
    ),
    (
        "Vehicle.Controller.Body.Mirror.Left.AdjustCmd",
        "Body.Mirror.Left.AdjustCmd",
    ),
    (
        "Vehicle.Controller.Body.Mirror.Left.FoldCmd",
        "Body.Mirror.Left.FoldCmd",
    ),
    (
        "Vehicle.Controller.Body.Mirror.Right.AdjustCmd",
        "Body.Mirror.Right.AdjustCmd",
    ),
    (
        "Vehicle.Controller.Body.Mirror.Right.FoldCmd",
        "Body.Mirror.Right.FoldCmd",
    ),
    (
        "Vehicle.Controller.Body.PEPS.ApproachKeys",
        "Body.PEPS.ApproachKeys",
    ),
    (
        "Vehicle.Controller.Body.PEPS.ApproachPoll",
        "Body.PEPS.ApproachPoll",
    ),
    (
        "Vehicle.Controller.Body.PEPS.ApproachPollInterval",
        "Body.PEPS.ApproachPollInterval",
    ),
    (
        "Vehicle.Controller.Body.PEPS.ApproachState",
        "Body.PEPS.ApproachState",
    ),
    (
        "Vehicle.Controller.Body.PEPS.BleChallenge",
        "Body.PEPS.BleChallenge",
    ),
    (
        "Vehicle.Controller.Body.PEPS.KeyPresent",
        "Body.PEPS.KeyPresent",
    ),
    (
        "Vehicle.Controller.Body.PEPS.LfChallenge",
        "Body.PEPS.LfChallenge",
    ),
    (
        "Vehicle.Controller.Body.PEPS.LostKeyWarning",
        "Body.PEPS.LostKeyWarning",
    ),
    (
        "Vehicle.Controller.Body.PEPS.NfcAuthBypass",
        "Body.PEPS.NfcAuthBypass",
    ),
    (
        "Vehicle.Controller.Body.PEPS.NfcChallenge",
        "Body.PEPS.NfcChallenge",
    ),
    (
        "Vehicle.Controller.Body.Power.DelayedAccessory.IsActive",
        "Body.Power.DelayedAccessory.IsActive",
    ),
    (
        "Vehicle.Controller.Body.PowerChildLock.MasterStatus",
        "Body.PowerChildLock.MasterStatus",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Switch.Lock",
        "Body.Switches.DoorTrim.Row1.Left.LockButton",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Switch.Unlock",
        "Body.Switches.DoorTrim.Row1.Left.UnlockButton",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Switch.Lock",
        "Body.Switches.DoorTrim.Row1.Right.LockButton",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Switch.Unlock",
        "Body.Switches.DoorTrim.Row1.Right.UnlockButton",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Switch.Lock",
        "Body.Switches.DoorTrim.Row2.Left.LockButton",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Switch.Lock",
        "Body.Switches.DoorTrim.Row2.Right.LockButton",
    ),
    (
        "Vehicle.Body.Lights.Fog.Front.Switch.IsEngaged",
        "Body.Switches.Fog.Front.IsEngaged",
    ),
    (
        "Vehicle.Body.Lights.Fog.Rear.Switch.IsEngaged",
        "Body.Switches.Fog.Rear.IsEngaged",
    ),
    (
        "Vehicle.Body.Lights.Hazard.Switch.IsEngaged",
        "Body.Switches.Hazard.IsEngaged",
    ),
    (
        "Vehicle.Body.Lights.Beam.High.Switch.IsEngaged",
        "Body.Switches.HighBeam.IsEngaged",
    ),
    (
        "Vehicle.Body.Hood.ReleaseSwitch.IsPulled",
        "Body.Switches.Hood.Release.IsPulled",
    ),
    (
        "Vehicle.Body.Horn.Switch.IsPressed",
        "Body.Switches.Horn.IsPressed",
    ),
    (
        "Vehicle.PowerMode.IgnitionCylinder.Position",
        "Body.Switches.IgnitionCylinder.Position",
    ),
    (
        "Vehicle.Controller.Body.Switches.IgnitionCylinder.RemovalInhibited",
        "Body.Switches.IgnitionCylinder.RemovalInhibited",
    ),
    (
        "Vehicle.Body.Mirrors.Switch.Direction",
        "Body.Switches.Mirror.Direction",
    ),
    (
        "Vehicle.Body.Mirrors.Switch.Fold",
        "Body.Switches.Mirror.Fold",
    ),
    (
        "Vehicle.Body.Mirrors.Switch.Select",
        "Body.Switches.Mirror.Select",
    ),
    (
        "Vehicle.Cabin.ChildLock.Switch.IsPressed",
        "Body.Switches.PowerChildLock.IsPressed",
    ),
    (
        "Vehicle.Controller.Body.Switches.StartStop.BacklightDutyCycle",
        "Body.Switches.StartStop.BacklightDutyCycle",
    ),
    (
        "Vehicle.Controller.Body.Switches.StartStop.BacklightIntensity",
        "Body.Switches.StartStop.BacklightIntensity",
    ),
    (
        "Vehicle.PowerMode.StartStopSwitch.IsPressed",
        "Body.Switches.StartStop.IsPressed",
    ),
    (
        "Vehicle.Cabin.Sunroof.Switch.Detent",
        "Body.Switches.Sunroof.Detent",
    ),
    (
        "Vehicle.Body.Trunk.Rear.ReleaseSwitch.IsPressed",
        "Body.Switches.Trunk.Release.IsPressed",
    ),
    (
        "Vehicle.Body.Lights.DirectionIndicator.Switch.Direction",
        "Body.Switches.TurnIndicator.Direction",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Window.Switch.MasterDetent",
        "Body.Switches.Window.DriverMaster.Row1.Left.Detent",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Window.Switch.MasterDetent",
        "Body.Switches.Window.DriverMaster.Row1.Right.Detent",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Window.Switch.MasterDetent",
        "Body.Switches.Window.DriverMaster.Row2.Left.Detent",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Window.Switch.MasterDetent",
        "Body.Switches.Window.DriverMaster.Row2.Right.Detent",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Left.Window.Switch.LocalDetent",
        "Body.Switches.Window.Local.Row1.Left.Detent",
    ),
    (
        "Vehicle.Cabin.Door.Row1.Right.Window.Switch.LocalDetent",
        "Body.Switches.Window.Local.Row1.Right.Detent",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Left.Window.Switch.LocalDetent",
        "Body.Switches.Window.Local.Row2.Left.Detent",
    ),
    (
        "Vehicle.Cabin.Door.Row2.Right.Window.Switch.LocalDetent",
        "Body.Switches.Window.Local.Row2.Right.Detent",
    ),
    (
        "Vehicle.Controller.Body.Trunk.Rear.CloseCmd",
        "Body.Trunk.CloseCmd",
    ),
    (
        "Vehicle.Controller.Body.Trunk.Rear.ExteriorButton.IsPressed",
        "Body.Trunk.ExteriorButton.IsPressed",
    ),
    (
        "Vehicle.Controller.Body.Trunk.Rear.OpenCmd",
        "Body.Trunk.OpenCmd",
    ),
    (
        "Vehicle.Controller.Body.Windshield.Front.Washing.IsActive",
        "Body.Windshield.Front.Washing.IsActive",
    ),
    (
        "Vehicle.Controller.Body.Windshield.Rear.Washing.IsActive",
        "Body.Windshield.Rear.Washing.IsActive",
    ),
    (
        "Vehicle.Controller.Cabin.Light.Dome.SwitchPosition",
        "Cabin.Lights.Dome.SwitchPosition",
    ),
    (
        "Vehicle.Controller.Cabin.Lights.Ambient.Color",
        "Cabin.Lights.Ambient.Color",
    ),
    (
        "Vehicle.Controller.Cabin.Lights.Ambient.Intensity",
        "Cabin.Lights.Ambient.Intensity",
    ),
    ("Vehicle.Cabin.LockStatus", "Cabin.LockStatus"),
    (
        "Vehicle.Cabin.LockStatus.EventNum",
        "Cabin.LockStatus.EventNum",
    ),
    (
        "Vehicle.Cabin.LockStatus.LastRequestor",
        "Cabin.LockStatus.LastRequestor",
    ),
    (
        "Vehicle.Controller.Cabin.Seat.Row1.Left.IsHeatingOn",
        "Cabin.Seat.Row1.Left.IsHeatingOn",
    ),
    (
        "Vehicle.Controller.Cabin.Seat.Row1.Left.IsVentilationOn",
        "Cabin.Seat.Row1.Left.IsVentilationOn",
    ),
    (
        "Vehicle.Controller.Cabin.Seat.Row1.Right.IsHeatingOn",
        "Cabin.Seat.Row1.Right.IsHeatingOn",
    ),
    (
        "Vehicle.Controller.Cabin.Seat.Row1.Right.IsVentilationOn",
        "Cabin.Seat.Row1.Right.IsVentilationOn",
    ),
    (
        "Vehicle.Controller.Cabin.ValetMode.IsActive",
        "Cabin.ValetMode.IsActive",
    ),
    ("Vehicle.Chassis.Brake.IsApplied", "Chassis.Brake.IsApplied"),
    ("Vehicle.CrashDetected", "Vehicle.Safety.CrashDetected"),
    (
        "Vehicle.Controller.Starting.ImmobilizerStatus",
        "Vehicle.Starting.ImmobilizerStatus",
    ),
    ("Vehicle.Controller.Sunroof.MoveCmd", "Body.Sunroof.MoveCmd"),
    (
        "Vehicle.Controller.Sunroof.Shade.MoveCmd",
        "Body.Sunroof.Shade.MoveCmd",
    ),
    (
        "Vehicle.Simulation.BlePhone.1.ChallengeResponse",
        "Body.PEPS.Plant.BlePhone.1.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.BlePhone.1.LastObservedZone",
        "Body.PEPS.Plant.BlePhone.1.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.BlePhone.1.NfcTap",
        "Body.PEPS.Plant.BlePhone.1.NfcTap",
    ),
    (
        "Vehicle.Simulation.BlePhone.1.PlacedZone",
        "Body.PEPS.Plant.BlePhone.1.PlacedZone",
    ),
    (
        "Vehicle.Simulation.BlePhone.1.RssiResponse",
        "Body.PEPS.Plant.BlePhone.1.RssiResponse",
    ),
    (
        "Vehicle.Simulation.BlePhone.2.ChallengeResponse",
        "Body.PEPS.Plant.BlePhone.2.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.BlePhone.2.LastObservedZone",
        "Body.PEPS.Plant.BlePhone.2.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.BlePhone.2.NfcTap",
        "Body.PEPS.Plant.BlePhone.2.NfcTap",
    ),
    (
        "Vehicle.Simulation.BlePhone.2.PlacedZone",
        "Body.PEPS.Plant.BlePhone.2.PlacedZone",
    ),
    (
        "Vehicle.Simulation.BlePhone.2.RssiResponse",
        "Body.PEPS.Plant.BlePhone.2.RssiResponse",
    ),
    (
        "Vehicle.Simulation.Connectivity.BleLock",
        "Body.Connectivity.BleLock",
    ),
    (
        "Vehicle.Simulation.Connectivity.NfcCardPresent",
        "Body.Connectivity.NfcCardPresent",
    ),
    (
        "Vehicle.Simulation.Connectivity.NfcPhonePresent",
        "Body.Connectivity.NfcPhonePresent",
    ),
    (
        "Vehicle.Simulation.Connectivity.RemoteLock",
        "Body.Connectivity.RemoteLock",
    ),
    (
        "Vehicle.Simulation.KeyFob.1.ButtonPress",
        "Body.PEPS.Plant.KeyFob.1.ButtonPress",
    ),
    (
        "Vehicle.Simulation.KeyFob.1.ChallengeResponse",
        "Body.PEPS.Plant.KeyFob.1.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.1.LastObservedZone",
        "Body.PEPS.Plant.KeyFob.1.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.1.Paired",
        "Body.PEPS.Plant.KeyFob.1.Paired",
    ),
    (
        "Vehicle.Simulation.KeyFob.1.PlacedZone",
        "Body.PEPS.Plant.KeyFob.1.PlacedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.1.RfMessage",
        "Body.PEPS.Plant.KeyFob.1.RfMessage",
    ),
    (
        "Vehicle.Simulation.KeyFob.1.RssiResponse",
        "Body.PEPS.Plant.KeyFob.1.RssiResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.2.ButtonPress",
        "Body.PEPS.Plant.KeyFob.2.ButtonPress",
    ),
    (
        "Vehicle.Simulation.KeyFob.2.ChallengeResponse",
        "Body.PEPS.Plant.KeyFob.2.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.2.LastObservedZone",
        "Body.PEPS.Plant.KeyFob.2.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.2.Paired",
        "Body.PEPS.Plant.KeyFob.2.Paired",
    ),
    (
        "Vehicle.Simulation.KeyFob.2.PlacedZone",
        "Body.PEPS.Plant.KeyFob.2.PlacedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.2.RfMessage",
        "Body.PEPS.Plant.KeyFob.2.RfMessage",
    ),
    (
        "Vehicle.Simulation.KeyFob.2.RssiResponse",
        "Body.PEPS.Plant.KeyFob.2.RssiResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.3.ButtonPress",
        "Body.PEPS.Plant.KeyFob.3.ButtonPress",
    ),
    (
        "Vehicle.Simulation.KeyFob.3.ChallengeResponse",
        "Body.PEPS.Plant.KeyFob.3.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.3.LastObservedZone",
        "Body.PEPS.Plant.KeyFob.3.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.3.Paired",
        "Body.PEPS.Plant.KeyFob.3.Paired",
    ),
    (
        "Vehicle.Simulation.KeyFob.3.PlacedZone",
        "Body.PEPS.Plant.KeyFob.3.PlacedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.3.RfMessage",
        "Body.PEPS.Plant.KeyFob.3.RfMessage",
    ),
    (
        "Vehicle.Simulation.KeyFob.3.RssiResponse",
        "Body.PEPS.Plant.KeyFob.3.RssiResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.4.ButtonPress",
        "Body.PEPS.Plant.KeyFob.4.ButtonPress",
    ),
    (
        "Vehicle.Simulation.KeyFob.4.ChallengeResponse",
        "Body.PEPS.Plant.KeyFob.4.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.4.LastObservedZone",
        "Body.PEPS.Plant.KeyFob.4.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.4.Paired",
        "Body.PEPS.Plant.KeyFob.4.Paired",
    ),
    (
        "Vehicle.Simulation.KeyFob.4.PlacedZone",
        "Body.PEPS.Plant.KeyFob.4.PlacedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.4.RfMessage",
        "Body.PEPS.Plant.KeyFob.4.RfMessage",
    ),
    (
        "Vehicle.Simulation.KeyFob.4.RssiResponse",
        "Body.PEPS.Plant.KeyFob.4.RssiResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.5.ChallengeResponse",
        "Body.PEPS.Plant.KeyFob.5.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.5.LastObservedZone",
        "Body.PEPS.Plant.KeyFob.5.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.5.Paired",
        "Body.PEPS.Plant.KeyFob.5.Paired",
    ),
    (
        "Vehicle.Simulation.KeyFob.5.PlacedZone",
        "Body.PEPS.Plant.KeyFob.5.PlacedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.5.RssiResponse",
        "Body.PEPS.Plant.KeyFob.5.RssiResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.6.ChallengeResponse",
        "Body.PEPS.Plant.KeyFob.6.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.KeyFob.6.LastObservedZone",
        "Body.PEPS.Plant.KeyFob.6.LastObservedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.6.Paired",
        "Body.PEPS.Plant.KeyFob.6.Paired",
    ),
    (
        "Vehicle.Simulation.KeyFob.6.PlacedZone",
        "Body.PEPS.Plant.KeyFob.6.PlacedZone",
    ),
    (
        "Vehicle.Simulation.KeyFob.6.RssiResponse",
        "Body.PEPS.Plant.KeyFob.6.RssiResponse",
    ),
    (
        "Vehicle.Simulation.NfcCard.1.ChallengeResponse",
        "Body.PEPS.Plant.NfcCard.1.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.NfcCard.1.Position",
        "Body.PEPS.Plant.NfcCard.1.Position",
    ),
    (
        "Vehicle.Simulation.NfcCard.2.ChallengeResponse",
        "Body.PEPS.Plant.NfcCard.2.ChallengeResponse",
    ),
    (
        "Vehicle.Simulation.NfcCard.2.Position",
        "Body.PEPS.Plant.NfcCard.2.Position",
    ),
    (
        "Vehicle.Simulation.TestFixtures.DoesNotExist",
        "Body.DoesNotExist",
    ),
    // Transmission — canonical `Vehicle.Powertrain.Transmission.*`
    // adopted internally as part of sub-PR 8a.  HMI cluster JS
    // still reads the pre-v6.0 names `Powertrain.Transmission.*`
    // (no `Vehicle.` prefix); the shim translates outbound /
    // inbound on the WS boundary.
    (
        "Vehicle.Powertrain.Transmission.CurrentGear",
        "Powertrain.Transmission.CurrentGear",
    ),
    (
        "Vehicle.Powertrain.Transmission.SelectedGear",
        "Powertrain.Transmission.SelectedGear",
    ),
    (
        "Vehicle.Powertrain.Transmission.ShiftLockEngaged",
        "Powertrain.Transmission.ShiftLockEngaged",
    ),
];

/// Translate a canonical bus path to the legacy name the HMI expects.
/// Falls through unchanged when there is no alias.
pub fn to_hmi(canonical: VssPath) -> VssPath {
    HMI_ALIASES
        .iter()
        .find(|(c, _)| *c == canonical)
        .map(|(_, legacy)| *legacy)
        .unwrap_or(canonical)
}

/// Translate a legacy HMI path to its canonical bus equivalent.
/// Falls through unchanged when there is no alias (the caller then
/// matches against the canonical signal lists and rejects unknowns).
pub fn from_hmi(legacy: &str) -> &str {
    HMI_ALIASES
        .iter()
        .find(|(_, l)| *l == legacy)
        .map(|(canon, _)| *canon)
        .unwrap_or(legacy)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_every_alias() {
        for (canon, legacy) in HMI_ALIASES {
            assert_eq!(to_hmi(canon), *legacy, "to_hmi({canon})");
            assert_eq!(from_hmi(legacy), *canon, "from_hmi({legacy})");
        }
    }

    #[test]
    fn unknown_paths_pass_through() {
        assert_eq!(
            to_hmi("Vehicle.Nonexistent.Path"),
            "Vehicle.Nonexistent.Path"
        );
        assert_eq!(from_hmi("Body.Nonexistent.Path"), "Body.Nonexistent.Path");
    }

    #[test]
    fn aliases_are_unique_both_directions() {
        use std::collections::HashSet;
        let canon: HashSet<_> = HMI_ALIASES.iter().map(|(c, _)| *c).collect();
        let legacy: HashSet<_> = HMI_ALIASES.iter().map(|(_, l)| *l).collect();
        assert_eq!(canon.len(), HMI_ALIASES.len(), "duplicate canonical key");
        assert_eq!(legacy.len(), HMI_ALIASES.len(), "duplicate legacy key");
    }
}
