//! Stable VSS signal ID constants.
//!
//! In production, this file would be auto-generated by `vspec2id` from the
//! combined VSS base + overlay catalog. These IDs are used in the IPC wire
//! format and must match the Safety Monitor's compiled lookup table.

use crate::signal_bus::VssPath;

/// Maps a VSS path string to its stable 32-bit signal ID.
/// Returns `None` for unknown paths.
pub fn path_to_id(path: VssPath) -> Option<u32> {
    match path {
        // Vehicle power state (powertrain-agnostic — standard VSS v4.0)
        "Vehicle.LowVoltageSystemState" => Some(0x0001_0001),
        "Vehicle.Powertrain.Type" => Some(0x0001_0002),

        // Lights
        "Body.Lights.Beam.Low.IsOn" => Some(0x0002_0001),
        "Body.Lights.Beam.High.IsOn" => Some(0x0002_0002),
        "Body.Lights.Running.IsOn" => Some(0x0002_0003),
        "Body.Lights.Parking.IsOn" => Some(0x0002_0004),
        "Body.Lights.Fog.Front.IsOn" => Some(0x0002_0005),
        "Body.Lights.Fog.Rear.IsOn" => Some(0x0002_0006),
        "Body.Lights.Brake.IsActive" => Some(0x0002_0007),
        "Body.Lights.Backup.IsActive" => Some(0x0002_0008),
        "Body.Lights.LicensePlate.IsOn" => Some(0x0002_0009),
        "Body.Lights.DirectionIndicator.Left.IsSignaling" => Some(0x0002_000A),
        "Body.Lights.DirectionIndicator.Right.IsSignaling" => Some(0x0002_000B),
        "Body.Lights.Hazard.IsSignaling" => Some(0x0002_000C),

        // Direction indicator lamp state (plant model outputs).
        // Three physical lamps per side: Front, Side (mirror repeater), Rear.
        "Body.Lights.DirectionIndicator.Left.Lamp.Front.IsOn" => Some(0x0002_000D),
        "Body.Lights.DirectionIndicator.Left.Lamp.Side.IsOn" => Some(0x0002_000E),
        "Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsOn" => Some(0x0002_000F),
        "Body.Lights.DirectionIndicator.Right.Lamp.Front.IsOn" => Some(0x0002_0010),
        "Body.Lights.DirectionIndicator.Right.Lamp.Side.IsOn" => Some(0x0002_0011),
        "Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsOn" => Some(0x0002_0012),
        "Body.Lights.DirectionIndicator.Left.Lamp.Front.IsDefect" => Some(0x0002_0013),
        "Body.Lights.DirectionIndicator.Left.Lamp.Side.IsDefect" => Some(0x0002_0014),
        "Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsDefect" => Some(0x0002_0015),
        "Body.Lights.DirectionIndicator.Right.Lamp.Front.IsDefect" => Some(0x0002_0016),
        "Body.Lights.DirectionIndicator.Right.Lamp.Side.IsDefect" => Some(0x0002_0017),
        "Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsDefect" => Some(0x0002_0018),

        // Windshield
        "Body.Windshield.Front.Wiping.Mode" => Some(0x0003_0001),
        "Body.Windshield.Front.Wiping.Intensity" => Some(0x0003_0002),
        "Body.Windshield.Front.Washing.IsActive" => Some(0x0003_0003),
        "Body.Windshield.Rear.Wiping.Mode" => Some(0x0003_0004),
        "Body.Windshield.Rear.Washing.IsActive" => Some(0x0003_0005),

        // Mirrors
        "Body.Mirrors.Left.IsFolded" => Some(0x0004_0001),
        "Body.Mirrors.Left.IsHeatingOn" => Some(0x0004_0002),
        "Body.Mirrors.Left.Tilt" => Some(0x0004_0003),
        "Body.Mirrors.Left.Pan" => Some(0x0004_0004),
        "Body.Mirrors.Right.IsFolded" => Some(0x0004_0005),
        "Body.Mirrors.Right.IsHeatingOn" => Some(0x0004_0006),
        "Body.Mirrors.Right.Tilt" => Some(0x0004_0007),
        "Body.Mirrors.Right.Pan" => Some(0x0004_0008),

        // Doors Row1 Left
        "Body.Doors.Row1.Left.IsOpen" => Some(0x0005_0001),
        "Body.Doors.Row1.Left.IsLocked" => Some(0x0005_0002),
        "Body.Doors.Row1.Left.LatchStatus" => Some(0x0005_0003),
        "Body.Doors.Row1.Left.IsChildLockActive" => Some(0x0005_0004),
        "Body.Doors.Row1.Left.Window.Position" => Some(0x0005_0005),
        "Body.Doors.Row1.Left.IsDoubleLocked" => Some(0x0005_0006),

        // Doors Row1 Right
        "Body.Doors.Row1.Right.IsOpen" => Some(0x0005_0011),
        "Body.Doors.Row1.Right.IsLocked" => Some(0x0005_0012),
        "Body.Doors.Row1.Right.LatchStatus" => Some(0x0005_0013),
        "Body.Doors.Row1.Right.IsChildLockActive" => Some(0x0005_0014),
        "Body.Doors.Row1.Right.Window.Position" => Some(0x0005_0015),
        "Body.Doors.Row1.Right.IsDoubleLocked" => Some(0x0005_0016),

        // Doors Row2 Left
        "Body.Doors.Row2.Left.IsOpen" => Some(0x0005_0021),
        "Body.Doors.Row2.Left.IsLocked" => Some(0x0005_0022),
        "Body.Doors.Row2.Left.LatchStatus" => Some(0x0005_0023),
        "Body.Doors.Row2.Left.IsChildLockActive" => Some(0x0005_0024),
        "Body.Doors.Row2.Left.Window.Position" => Some(0x0005_0025),
        "Body.Doors.Row2.Left.IsDoubleLocked" => Some(0x0005_0026),

        // Doors Row2 Right
        "Body.Doors.Row2.Right.IsOpen" => Some(0x0005_0031),
        "Body.Doors.Row2.Right.IsLocked" => Some(0x0005_0032),
        "Body.Doors.Row2.Right.LatchStatus" => Some(0x0005_0033),
        "Body.Doors.Row2.Right.IsChildLockActive" => Some(0x0005_0034),
        "Body.Doors.Row2.Right.Window.Position" => Some(0x0005_0035),
        "Body.Doors.Row2.Right.IsDoubleLocked" => Some(0x0005_0036),

        // Body misc
        "Body.Hood.IsOpen" => Some(0x0006_0001),
        "Body.Trunk.IsOpen" => Some(0x0006_0002),
        "Body.Trunk.IsLocked" => Some(0x0006_0003),
        "Body.Horn.IsActive" => Some(0x0006_0004),
        "Body.FuelLid.IsOpen" => Some(0x0006_0005),
        "Body.ChargeLid.IsOpen" => Some(0x0006_0006),

        // Sunroof
        "Body.Sunroof.Position" => Some(0x0007_0001),
        "Body.Sunroof.Shade.Position" => Some(0x0007_0002),

        // Cabin Lights
        "Cabin.Lights.IsDomeOn" => Some(0x0008_0001),
        "Cabin.Lights.IsGloveBoxOn" => Some(0x0008_0002),
        "Cabin.Lights.Ambient.Intensity" => Some(0x0008_0003),
        "Cabin.Lights.Ambient.Color" => Some(0x0008_0004),

        // HVAC
        "Cabin.HVAC.IsAirConditioningActive" => Some(0x0009_0001),
        "Cabin.HVAC.IsRecirculationActive" => Some(0x0009_0002),
        "Cabin.HVAC.IsFrontDefrosterActive" => Some(0x0009_0003),
        "Cabin.HVAC.IsRearDefrosterActive" => Some(0x0009_0004),
        "Cabin.HVAC.Station.Row1.Left.Temperature" => Some(0x0009_0010),
        "Cabin.HVAC.Station.Row1.Left.FanSpeed" => Some(0x0009_0011),
        "Cabin.HVAC.Station.Row1.Left.AirDistribution" => Some(0x0009_0012),
        "Cabin.HVAC.Station.Row1.Right.Temperature" => Some(0x0009_0020),
        "Cabin.HVAC.Station.Row1.Right.FanSpeed" => Some(0x0009_0021),
        "Cabin.HVAC.Station.Row1.Right.AirDistribution" => Some(0x0009_0022),

        // Seats
        "Cabin.Seat.Row1.Left.IsHeatingOn" => Some(0x000A_0001),
        "Cabin.Seat.Row1.Left.IsVentilationOn" => Some(0x000A_0002),
        "Cabin.Seat.Row1.Left.HeatingLevel" => Some(0x000A_0003),
        "Cabin.Seat.Row1.Right.IsHeatingOn" => Some(0x000A_0011),
        "Cabin.Seat.Row1.Right.IsVentilationOn" => Some(0x000A_0012),
        "Cabin.Seat.Row1.Right.HeatingLevel" => Some(0x000A_0013),

        // PEPS synthetic signal
        "Body.PEPS.KeyPresent" => Some(0x000B_0001),

        // Switch / stalk inputs (overlay — not in standard VSS v4.0)
        "Body.Switches.Hazard.IsEngaged" => Some(0x000D_0001),
        "Body.Switches.TurnIndicator.Direction" => Some(0x000D_0002),
        "Body.Switches.HighBeam.IsEngaged" => Some(0x000D_0003),
        "Chassis.ParkingBrake.IsEngaged" => Some(0x000D_0004),

        // Chassis / Powertrain (sensor inputs)
        "Chassis.Brake.PedalPosition" => Some(0x000C_0001),
        "Powertrain.Transmission.CurrentGear" => Some(0x000C_0002),
        "Vehicle.Speed" => Some(0x000C_0003),
        "Body.Lights.LightSwitch" => Some(0x000C_0004),

        // Door lock inputs (overlay — DoorLockInputs.vspec)
        "Body.Switches.DoorTrim.Row1.Left.LockButton" => Some(0x000E_0001),
        "Body.Switches.DoorTrim.Row1.Right.LockButton" => Some(0x000E_0002),
        "Body.Switches.DoorTrim.Row2.Left.LockButton" => Some(0x000E_0003),
        "Body.Switches.DoorTrim.Row2.Right.LockButton" => Some(0x000E_0004),
        "Body.Switches.Keyfob.LockButton" => Some(0x000E_0010),
        "Body.Connectivity.RemoteLock" => Some(0x000E_0020),
        "Body.Connectivity.BleLock" => Some(0x000E_0021),
        "Body.Connectivity.NfcCardPresent" => Some(0x000E_0030),
        "Body.Connectivity.NfcPhonePresent" => Some(0x000E_0031),

        // Door removed sensors (removable doors — Bronco, Wrangler)
        "Body.Doors.Row1.Left.IsRemoved" => Some(0x000E_0040),
        "Body.Doors.Row1.Right.IsRemoved" => Some(0x000E_0041),
        "Body.Doors.Row2.Left.IsRemoved" => Some(0x000E_0042),
        "Body.Doors.Row2.Right.IsRemoved" => Some(0x000E_0043),

        // Safety signals
        "Vehicle.Safety.CrashDetected" => Some(0x000F_0001),

        // PEPS plant model — key fob zones
        "Body.PEPS.Plant.KeyFob.1.Zone" => Some(0x0010_0001),
        "Body.PEPS.Plant.KeyFob.2.Zone" => Some(0x0010_0002),
        "Body.PEPS.Plant.KeyFob.3.Zone" => Some(0x0010_0003),
        "Body.PEPS.Plant.KeyFob.4.Zone" => Some(0x0010_0004),
        "Body.PEPS.Plant.KeyFob.5.Zone" => Some(0x0010_0005),
        "Body.PEPS.Plant.KeyFob.6.Zone" => Some(0x0010_0006),
        // PEPS plant model — key fob button presses
        "Body.PEPS.Plant.KeyFob.1.ButtonPress" => Some(0x0010_0011),
        "Body.PEPS.Plant.KeyFob.2.ButtonPress" => Some(0x0010_0012),
        "Body.PEPS.Plant.KeyFob.3.ButtonPress" => Some(0x0010_0013),
        "Body.PEPS.Plant.KeyFob.4.ButtonPress" => Some(0x0010_0014),
        // PEPS plant model — key fob pairing
        "Body.PEPS.Plant.KeyFob.1.Paired" => Some(0x0010_0021),
        "Body.PEPS.Plant.KeyFob.2.Paired" => Some(0x0010_0022),
        "Body.PEPS.Plant.KeyFob.3.Paired" => Some(0x0010_0023),
        "Body.PEPS.Plant.KeyFob.4.Paired" => Some(0x0010_0024),
        "Body.PEPS.Plant.KeyFob.5.Paired" => Some(0x0010_0025),
        "Body.PEPS.Plant.KeyFob.6.Paired" => Some(0x0010_0026),
        // PEPS plant model — key fob challenge responses
        "Body.PEPS.Plant.KeyFob.1.ChallengeResponse" => Some(0x0010_0031),
        "Body.PEPS.Plant.KeyFob.2.ChallengeResponse" => Some(0x0010_0032),
        "Body.PEPS.Plant.KeyFob.3.ChallengeResponse" => Some(0x0010_0033),
        "Body.PEPS.Plant.KeyFob.4.ChallengeResponse" => Some(0x0010_0034),
        "Body.PEPS.Plant.KeyFob.5.ChallengeResponse" => Some(0x0010_0035),
        "Body.PEPS.Plant.KeyFob.6.ChallengeResponse" => Some(0x0010_0036),
        // PEPS plant model — key fob RSSI responses
        "Body.PEPS.Plant.KeyFob.1.RssiResponse" => Some(0x0010_0041),
        "Body.PEPS.Plant.KeyFob.2.RssiResponse" => Some(0x0010_0042),
        "Body.PEPS.Plant.KeyFob.3.RssiResponse" => Some(0x0010_0043),
        "Body.PEPS.Plant.KeyFob.4.RssiResponse" => Some(0x0010_0044),
        "Body.PEPS.Plant.KeyFob.5.RssiResponse" => Some(0x0010_0045),
        "Body.PEPS.Plant.KeyFob.6.RssiResponse" => Some(0x0010_0046),
        // PEPS plant model — key fob RF messages
        "Body.PEPS.Plant.KeyFob.1.RfMessage" => Some(0x0010_0051),
        "Body.PEPS.Plant.KeyFob.2.RfMessage" => Some(0x0010_0052),
        "Body.PEPS.Plant.KeyFob.3.RfMessage" => Some(0x0010_0053),
        "Body.PEPS.Plant.KeyFob.4.RfMessage" => Some(0x0010_0054),
        // PEPS plant model — BLE phone zones
        "Body.PEPS.Plant.BlePhone.1.Zone" => Some(0x0011_0001),
        "Body.PEPS.Plant.BlePhone.2.Zone" => Some(0x0011_0002),
        // PEPS plant model — BLE phone challenge responses
        "Body.PEPS.Plant.BlePhone.1.ChallengeResponse" => Some(0x0011_0011),
        "Body.PEPS.Plant.BlePhone.2.ChallengeResponse" => Some(0x0011_0012),
        // PEPS plant model — BLE phone RSSI responses
        "Body.PEPS.Plant.BlePhone.1.RssiResponse" => Some(0x0011_0021),
        "Body.PEPS.Plant.BlePhone.2.RssiResponse" => Some(0x0011_0022),
        // PEPS plant model — NFC card positions
        "Body.PEPS.Plant.NfcCard.1.Position" => Some(0x0012_0001),
        "Body.PEPS.Plant.NfcCard.2.Position" => Some(0x0012_0002),
        // PEPS plant model — NFC card challenge responses
        "Body.PEPS.Plant.NfcCard.1.ChallengeResponse" => Some(0x0012_0011),
        "Body.PEPS.Plant.NfcCard.2.ChallengeResponse" => Some(0x0012_0012),
        // PEPS vehicle-side challenge/poll signals
        "Body.PEPS.LfChallenge" => Some(0x0013_0001),
        "Body.PEPS.BleChallenge" => Some(0x0013_0002),
        "Body.PEPS.NfcChallenge" => Some(0x0013_0003),
        "Body.PEPS.ApproachPoll" => Some(0x0013_0004),

        _ => None,
    }
}

/// Returns the VSS path for a given signal ID, or `None` if unknown.
pub fn id_to_path(id: u32) -> Option<VssPath> {
    // Reverse lookup — in production this would be a generated phf map.
    ALL_SIGNALS
        .iter()
        .find(|(_, sid)| *sid == id)
        .map(|(p, _)| *p)
}

/// Complete signal catalog: (path, id) pairs.
pub const ALL_SIGNALS: &[(VssPath, u32)] = &[
    ("Vehicle.LowVoltageSystemState", 0x0001_0001),
    ("Vehicle.Powertrain.Type", 0x0001_0002),
    ("Body.Lights.Beam.Low.IsOn", 0x0002_0001),
    ("Body.Lights.Beam.High.IsOn", 0x0002_0002),
    ("Body.Lights.Running.IsOn", 0x0002_0003),
    ("Body.Lights.Parking.IsOn", 0x0002_0004),
    ("Body.Lights.Fog.Front.IsOn", 0x0002_0005),
    ("Body.Lights.Fog.Rear.IsOn", 0x0002_0006),
    ("Body.Lights.Brake.IsActive", 0x0002_0007),
    ("Body.Lights.Backup.IsActive", 0x0002_0008),
    ("Body.Lights.LicensePlate.IsOn", 0x0002_0009),
    (
        "Body.Lights.DirectionIndicator.Left.IsSignaling",
        0x0002_000A,
    ),
    (
        "Body.Lights.DirectionIndicator.Right.IsSignaling",
        0x0002_000B,
    ),
    ("Body.Lights.Hazard.IsSignaling", 0x0002_000C),
    (
        "Body.Lights.DirectionIndicator.Left.Lamp.Front.IsOn",
        0x0002_000D,
    ),
    (
        "Body.Lights.DirectionIndicator.Left.Lamp.Side.IsOn",
        0x0002_000E,
    ),
    (
        "Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsOn",
        0x0002_000F,
    ),
    (
        "Body.Lights.DirectionIndicator.Right.Lamp.Front.IsOn",
        0x0002_0010,
    ),
    (
        "Body.Lights.DirectionIndicator.Right.Lamp.Side.IsOn",
        0x0002_0011,
    ),
    (
        "Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsOn",
        0x0002_0012,
    ),
    (
        "Body.Lights.DirectionIndicator.Left.Lamp.Front.IsDefect",
        0x0002_0013,
    ),
    (
        "Body.Lights.DirectionIndicator.Left.Lamp.Side.IsDefect",
        0x0002_0014,
    ),
    (
        "Body.Lights.DirectionIndicator.Left.Lamp.Rear.IsDefect",
        0x0002_0015,
    ),
    (
        "Body.Lights.DirectionIndicator.Right.Lamp.Front.IsDefect",
        0x0002_0016,
    ),
    (
        "Body.Lights.DirectionIndicator.Right.Lamp.Side.IsDefect",
        0x0002_0017,
    ),
    (
        "Body.Lights.DirectionIndicator.Right.Lamp.Rear.IsDefect",
        0x0002_0018,
    ),
    ("Body.Windshield.Front.Wiping.Mode", 0x0003_0001),
    ("Body.Windshield.Front.Wiping.Intensity", 0x0003_0002),
    ("Body.Windshield.Front.Washing.IsActive", 0x0003_0003),
    ("Body.Windshield.Rear.Wiping.Mode", 0x0003_0004),
    ("Body.Windshield.Rear.Washing.IsActive", 0x0003_0005),
    ("Body.Mirrors.Left.IsFolded", 0x0004_0001),
    ("Body.Mirrors.Left.IsHeatingOn", 0x0004_0002),
    ("Body.Mirrors.Left.Tilt", 0x0004_0003),
    ("Body.Mirrors.Left.Pan", 0x0004_0004),
    ("Body.Mirrors.Right.IsFolded", 0x0004_0005),
    ("Body.Mirrors.Right.IsHeatingOn", 0x0004_0006),
    ("Body.Mirrors.Right.Tilt", 0x0004_0007),
    ("Body.Mirrors.Right.Pan", 0x0004_0008),
    ("Body.Doors.Row1.Left.IsOpen", 0x0005_0001),
    ("Body.Doors.Row1.Left.IsLocked", 0x0005_0002),
    ("Body.Doors.Row1.Left.LatchStatus", 0x0005_0003),
    ("Body.Doors.Row1.Left.IsChildLockActive", 0x0005_0004),
    ("Body.Doors.Row1.Left.Window.Position", 0x0005_0005),
    ("Body.Doors.Row1.Left.IsDoubleLocked", 0x0005_0006),
    ("Body.Doors.Row1.Right.IsOpen", 0x0005_0011),
    ("Body.Doors.Row1.Right.IsLocked", 0x0005_0012),
    ("Body.Doors.Row1.Right.LatchStatus", 0x0005_0013),
    ("Body.Doors.Row1.Right.IsChildLockActive", 0x0005_0014),
    ("Body.Doors.Row1.Right.Window.Position", 0x0005_0015),
    ("Body.Doors.Row1.Right.IsDoubleLocked", 0x0005_0016),
    ("Body.Doors.Row2.Left.IsOpen", 0x0005_0021),
    ("Body.Doors.Row2.Left.IsLocked", 0x0005_0022),
    ("Body.Doors.Row2.Left.LatchStatus", 0x0005_0023),
    ("Body.Doors.Row2.Left.IsChildLockActive", 0x0005_0024),
    ("Body.Doors.Row2.Left.Window.Position", 0x0005_0025),
    ("Body.Doors.Row2.Left.IsDoubleLocked", 0x0005_0026),
    ("Body.Doors.Row2.Right.IsOpen", 0x0005_0031),
    ("Body.Doors.Row2.Right.IsLocked", 0x0005_0032),
    ("Body.Doors.Row2.Right.LatchStatus", 0x0005_0033),
    ("Body.Doors.Row2.Right.IsChildLockActive", 0x0005_0034),
    ("Body.Doors.Row2.Right.Window.Position", 0x0005_0035),
    ("Body.Doors.Row2.Right.IsDoubleLocked", 0x0005_0036),
    ("Body.Hood.IsOpen", 0x0006_0001),
    ("Body.Trunk.IsOpen", 0x0006_0002),
    ("Body.Trunk.IsLocked", 0x0006_0003),
    ("Body.Horn.IsActive", 0x0006_0004),
    ("Body.FuelLid.IsOpen", 0x0006_0005),
    ("Body.ChargeLid.IsOpen", 0x0006_0006),
    ("Body.Sunroof.Position", 0x0007_0001),
    ("Body.Sunroof.Shade.Position", 0x0007_0002),
    ("Cabin.Lights.IsDomeOn", 0x0008_0001),
    ("Cabin.Lights.IsGloveBoxOn", 0x0008_0002),
    ("Cabin.Lights.Ambient.Intensity", 0x0008_0003),
    ("Cabin.Lights.Ambient.Color", 0x0008_0004),
    ("Cabin.HVAC.IsAirConditioningActive", 0x0009_0001),
    ("Cabin.HVAC.IsRecirculationActive", 0x0009_0002),
    ("Cabin.HVAC.IsFrontDefrosterActive", 0x0009_0003),
    ("Cabin.HVAC.IsRearDefrosterActive", 0x0009_0004),
    ("Cabin.HVAC.Station.Row1.Left.Temperature", 0x0009_0010),
    ("Cabin.HVAC.Station.Row1.Left.FanSpeed", 0x0009_0011),
    ("Cabin.HVAC.Station.Row1.Left.AirDistribution", 0x0009_0012),
    ("Cabin.HVAC.Station.Row1.Right.Temperature", 0x0009_0020),
    ("Cabin.HVAC.Station.Row1.Right.FanSpeed", 0x0009_0021),
    ("Cabin.HVAC.Station.Row1.Right.AirDistribution", 0x0009_0022),
    ("Cabin.Seat.Row1.Left.IsHeatingOn", 0x000A_0001),
    ("Cabin.Seat.Row1.Left.IsVentilationOn", 0x000A_0002),
    ("Cabin.Seat.Row1.Left.HeatingLevel", 0x000A_0003),
    ("Cabin.Seat.Row1.Right.IsHeatingOn", 0x000A_0011),
    ("Cabin.Seat.Row1.Right.IsVentilationOn", 0x000A_0012),
    ("Cabin.Seat.Row1.Right.HeatingLevel", 0x000A_0013),
    ("Body.PEPS.KeyPresent", 0x000B_0001),
    // Switch / stalk inputs (overlay)
    ("Body.Switches.Hazard.IsEngaged", 0x000D_0001),
    ("Body.Switches.TurnIndicator.Direction", 0x000D_0002),
    ("Body.Switches.HighBeam.IsEngaged", 0x000D_0003),
    ("Chassis.ParkingBrake.IsEngaged", 0x000D_0004),
    // Chassis / Powertrain
    ("Chassis.Brake.PedalPosition", 0x000C_0001),
    ("Powertrain.Transmission.CurrentGear", 0x000C_0002),
    ("Vehicle.Speed", 0x000C_0003),
    ("Body.Lights.LightSwitch", 0x000C_0004),
    // Door lock inputs (overlay — DoorLockInputs.vspec)
    ("Body.Switches.DoorTrim.Row1.Left.LockButton", 0x000E_0001),
    ("Body.Switches.DoorTrim.Row1.Right.LockButton", 0x000E_0002),
    ("Body.Switches.DoorTrim.Row2.Left.LockButton", 0x000E_0003),
    ("Body.Switches.DoorTrim.Row2.Right.LockButton", 0x000E_0004),
    ("Body.Switches.Keyfob.LockButton", 0x000E_0010),
    ("Body.Connectivity.RemoteLock", 0x000E_0020),
    ("Body.Connectivity.BleLock", 0x000E_0021),
    ("Body.Connectivity.NfcCardPresent", 0x000E_0030),
    ("Body.Connectivity.NfcPhonePresent", 0x000E_0031),
    // Door removed sensors (removable doors)
    ("Body.Doors.Row1.Left.IsRemoved", 0x000E_0040),
    ("Body.Doors.Row1.Right.IsRemoved", 0x000E_0041),
    ("Body.Doors.Row2.Left.IsRemoved", 0x000E_0042),
    ("Body.Doors.Row2.Right.IsRemoved", 0x000E_0043),
    // Safety signals
    ("Vehicle.Safety.CrashDetected", 0x000F_0001),
    // PEPS plant model — key fob zones
    ("Body.PEPS.Plant.KeyFob.1.Zone", 0x0010_0001),
    ("Body.PEPS.Plant.KeyFob.2.Zone", 0x0010_0002),
    ("Body.PEPS.Plant.KeyFob.3.Zone", 0x0010_0003),
    ("Body.PEPS.Plant.KeyFob.4.Zone", 0x0010_0004),
    ("Body.PEPS.Plant.KeyFob.5.Zone", 0x0010_0005),
    ("Body.PEPS.Plant.KeyFob.6.Zone", 0x0010_0006),
    // PEPS plant model — key fob button presses
    ("Body.PEPS.Plant.KeyFob.1.ButtonPress", 0x0010_0011),
    ("Body.PEPS.Plant.KeyFob.2.ButtonPress", 0x0010_0012),
    ("Body.PEPS.Plant.KeyFob.3.ButtonPress", 0x0010_0013),
    ("Body.PEPS.Plant.KeyFob.4.ButtonPress", 0x0010_0014),
    // PEPS plant model — key fob pairing
    ("Body.PEPS.Plant.KeyFob.1.Paired", 0x0010_0021),
    ("Body.PEPS.Plant.KeyFob.2.Paired", 0x0010_0022),
    ("Body.PEPS.Plant.KeyFob.3.Paired", 0x0010_0023),
    ("Body.PEPS.Plant.KeyFob.4.Paired", 0x0010_0024),
    ("Body.PEPS.Plant.KeyFob.5.Paired", 0x0010_0025),
    ("Body.PEPS.Plant.KeyFob.6.Paired", 0x0010_0026),
    // PEPS plant model — key fob challenge responses
    ("Body.PEPS.Plant.KeyFob.1.ChallengeResponse", 0x0010_0031),
    ("Body.PEPS.Plant.KeyFob.2.ChallengeResponse", 0x0010_0032),
    ("Body.PEPS.Plant.KeyFob.3.ChallengeResponse", 0x0010_0033),
    ("Body.PEPS.Plant.KeyFob.4.ChallengeResponse", 0x0010_0034),
    ("Body.PEPS.Plant.KeyFob.5.ChallengeResponse", 0x0010_0035),
    ("Body.PEPS.Plant.KeyFob.6.ChallengeResponse", 0x0010_0036),
    // PEPS plant model — key fob RSSI responses
    ("Body.PEPS.Plant.KeyFob.1.RssiResponse", 0x0010_0041),
    ("Body.PEPS.Plant.KeyFob.2.RssiResponse", 0x0010_0042),
    ("Body.PEPS.Plant.KeyFob.3.RssiResponse", 0x0010_0043),
    ("Body.PEPS.Plant.KeyFob.4.RssiResponse", 0x0010_0044),
    ("Body.PEPS.Plant.KeyFob.5.RssiResponse", 0x0010_0045),
    ("Body.PEPS.Plant.KeyFob.6.RssiResponse", 0x0010_0046),
    // PEPS plant model — key fob RF messages
    ("Body.PEPS.Plant.KeyFob.1.RfMessage", 0x0010_0051),
    ("Body.PEPS.Plant.KeyFob.2.RfMessage", 0x0010_0052),
    ("Body.PEPS.Plant.KeyFob.3.RfMessage", 0x0010_0053),
    ("Body.PEPS.Plant.KeyFob.4.RfMessage", 0x0010_0054),
    // PEPS plant model — BLE phone zones
    ("Body.PEPS.Plant.BlePhone.1.Zone", 0x0011_0001),
    ("Body.PEPS.Plant.BlePhone.2.Zone", 0x0011_0002),
    // PEPS plant model — BLE phone challenge responses
    ("Body.PEPS.Plant.BlePhone.1.ChallengeResponse", 0x0011_0011),
    ("Body.PEPS.Plant.BlePhone.2.ChallengeResponse", 0x0011_0012),
    // PEPS plant model — BLE phone RSSI responses
    ("Body.PEPS.Plant.BlePhone.1.RssiResponse", 0x0011_0021),
    ("Body.PEPS.Plant.BlePhone.2.RssiResponse", 0x0011_0022),
    // PEPS plant model — NFC card positions
    ("Body.PEPS.Plant.NfcCard.1.Position", 0x0012_0001),
    ("Body.PEPS.Plant.NfcCard.2.Position", 0x0012_0002),
    // PEPS plant model — NFC card challenge responses
    ("Body.PEPS.Plant.NfcCard.1.ChallengeResponse", 0x0012_0011),
    ("Body.PEPS.Plant.NfcCard.2.ChallengeResponse", 0x0012_0012),
    // PEPS vehicle-side challenge/poll signals
    ("Body.PEPS.LfChallenge", 0x0013_0001),
    ("Body.PEPS.BleChallenge", 0x0013_0002),
    ("Body.PEPS.NfcChallenge", 0x0013_0003),
    ("Body.PEPS.ApproachPoll", 0x0013_0004),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_to_id_known_signals() {
        assert_eq!(path_to_id("Body.Lights.Beam.Low.IsOn"), Some(0x0002_0001));
        assert_eq!(path_to_id("Body.PEPS.KeyPresent"), Some(0x000B_0001));
        assert_eq!(path_to_id("Vehicle.Speed"), Some(0x000C_0003));
    }

    #[test]
    fn path_to_id_unknown_returns_none() {
        assert_eq!(path_to_id("Body.DoesNotExist"), None);
    }

    #[test]
    fn id_to_path_roundtrip() {
        for (path, id) in ALL_SIGNALS {
            assert_eq!(path_to_id(path), Some(*id));
            assert_eq!(id_to_path(*id), Some(*path));
        }
    }

    #[test]
    fn no_duplicate_ids() {
        let mut ids: Vec<u32> = ALL_SIGNALS.iter().map(|(_, id)| *id).collect();
        ids.sort();
        ids.dedup();
        assert_eq!(
            ids.len(),
            ALL_SIGNALS.len(),
            "duplicate signal IDs detected"
        );
    }
}
